// Carga inicial. Só é usada na primeira vez que o app roda no navegador
// (depois disso tudo passa a viver no localStorage e pode ser editado livremente).

const today = new Date().toISOString().slice(0, 10);

export const seedLeads = [
  {
    id: 'lead-1',
    name: 'Studio Tauane Gabriela',
    niche: 'Personal Trainer',
    phone: '+5541995540052',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'alta',
    notes: 'Estúdio recém aberto, 2 avaliações no Google.',
    tags: ['recém aberto'],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-2',
    name: 'Heitor Eurich Studio',
    niche: 'Personal Trainer',
    phone: '+5541985199280',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'alta',
    notes: 'Estúdio recém aberto, 3 avaliações no Google.',
    tags: ['recém aberto'],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-3',
    name: 'Maia & Ribas Advocacia',
    niche: 'Advocacia',
    phone: '+5541992779595',
    origin: 'busca_ativa',
    status: 'respondeu',
    priority: 'alta',
    notes:
      'Filial de escritório grande de Curitiba. Disse que pode ser mais pra frente, vai levar pra matriz. Mandei o preço fechado (R$600, 50/50, 48h) e ofereci montar uma proposta de layout pra ela levar pra matriz. Aguardando retorno.',
    tags: ['aguardando matriz'],
    lastContact: today,
    createdAt: today,
  },
  {
    id: 'lead-4',
    name: 'Buffet Star Happy SJP',
    niche: 'Eventos',
    phone: '+5541984795835',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'alta',
    notes: 'Espaço saindo do zero agora, só 2 avaliações.',
    tags: ['recém aberto'],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-5',
    name: 'ALTCON Contabilidade',
    niche: 'Contabilidade',
    phone: '+554133837066',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: 'Presença digital quase nula, 4 avaliações.',
    tags: [],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-6',
    name: 'Centro Odontológico SJP',
    niche: 'Odontologia',
    phone: '+554130351123',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: 'Clínica pequena, 6 avaliações.',
    tags: [],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-7',
    name: 'Escritório Acertha',
    niche: 'Contabilidade',
    phone: '+554130983747',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: 'Escritório pequeno, 6 avaliações.',
    tags: [],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-8',
    name: 'Kopex Contabilidade',
    niche: 'Contabilidade',
    phone: '+554133823671',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: 'Escritório pequeno, 7 avaliações.',
    tags: [],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-9',
    name: 'Carvalho & do Carmo Advogados',
    niche: 'Advocacia',
    phone: '+5541999233379',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: 'Escritório pequeno, decisor único, 11 avaliações.',
    tags: [],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-10',
    name: 'Buffet Alto Padrão',
    niche: 'Eventos',
    phone: '+554133820756',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: 'Espaço pequeno, 11 avaliações.',
    tags: [],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-11',
    name: 'Studio Rogério Martins',
    niche: 'Personal Trainer',
    phone: '+5541995112479',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: 'Estúdio pequeno, 11 avaliações.',
    tags: [],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-12',
    name: 'Smart Move Personal Trainer',
    niche: 'Personal Trainer',
    phone: '+5541991618725',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: '19 avaliações, pequeno.',
    tags: [],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-13',
    name: 'Dra. Andrea Castro',
    niche: 'Odontologia',
    phone: '+5541991212053',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: 'Marca pessoal, decisora única, 20 avaliações.',
    tags: [],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-14',
    name: 'KG Trainer',
    niche: 'Personal Trainer',
    phone: '+5541999271671',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: '20 avaliações, pequeno.',
    tags: [],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-15',
    name: 'Magic World Festas e Eventos',
    niche: 'Eventos',
    phone: '+5541991067254',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: '1 reclamação leve sobre agenda. Puxar gancho da agenda em tempo real.',
    tags: ['recuperação de imagem'],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-16',
    name: 'Dr. Matheus Tardeli',
    niche: 'Odontologia',
    phone: '+554130356226',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: 'Marca pessoal, odontopediatra, 18 avaliações.',
    tags: [],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-17',
    name: 'Dra. Evelyne Castella',
    niche: 'Odontologia',
    phone: '+5541999305081',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: 'Marca pessoal, odontopediatria, 25 avaliações.',
    tags: [],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-18',
    name: 'Rocha & Tormes Advogados',
    niche: 'Advocacia',
    phone: '+554130354797',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: 'Escritório pequeno, 23 avaliações.',
    tags: [],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-19',
    name: 'MAPPEN Contabilidade',
    niche: 'Contabilidade',
    phone: '+554132827223',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: 'Nota alta, escritório pequeno, 15 avaliações.',
    tags: [],
    lastContact: null,
    createdAt: today,
  },
  {
    id: 'lead-20',
    name: "Gabriella's Gastronomia",
    niche: 'Eventos',
    phone: '+5541997540132',
    origin: 'busca_ativa',
    status: 'novo',
    priority: 'media',
    notes: 'Decisora única, 29 avaliações.',
    tags: [],
    lastContact: null,
    createdAt: today,
  },
];
